bash

cat << 'PYEOF' > /home/claude/fill_plantilla.py
import openpyxl
from copy import copy

wb = openpyxl.load_workbook('/home/claude/Plantilla_prompts.xlsx')

# =============================================
# HOJA 1: Patrones de dinámica
# =============================================
ws1 = wb['Patrones de dinámica']

# Caso de uso / consulta base
ws1['C8'] = 'Salud y bienestar mental'
ws1['C9'] = 'Estrategias de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['C10'] = 'Elaborar una lista de estrategias prácticas de autocuidado que una persona adulta joven pueda aplicar en su rutina diaria para reducir el estrés y mejorar su bienestar mental.'
ws1['C12'] = 'Lista numerada con título breve y descripción de cada estrategia (máximo 3 líneas por ítem).'
ws1['C13'] = 'Respuestas concretas, aplicables y basadas en evidencia. Sin tecnicismos innecesarios.'
ws1['C14'] = 'Técnicas de respiración, ejercicio, alimentación, descanso, gestión del tiempo y conexión social.'
ws1['C15'] = 'No proporciones diagnósticos clínicos ni recomendaciones de medicamentos. Enfócate en hábitos del día a día. No menciones la tarea que se te encomendó en tu respuesta.'

# Chatbot: Claude en todas las versiones (filas 21: C,G,K,O,S,W,AA)
for col in ['C', 'G', 'K', 'O', 'S', 'W', 'AA']:
    ws1[f'{col}21'] = 'Claude'

# ---- PE01 - INFORMACIÓN NUEVA ----
# Aplicación V0, VP, VR
ws1['C23'] = '[--]'
ws1['D23'] = 'Usaremos PE01 para inyectar un fragmento de investigación reciente sobre el cortisol y el sueño, de modo que el modelo contextualice sus recomendaciones en base a ese dato nuevo.'
ws1['E23'] = 'Usaremos PE03 (Asumir Persona) además de PE01 porque al combinar un dato nuevo con el rol de psicólogo de bienestar, la respuesta gana tanto rigor informativo como tono empático y práctico.'

# Prompts PE01
ws1['C25'] = 'Dame una lista de estrategias prácticas de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['D25'] = 'Considera el siguiente dato reciente: según un estudio de 2023 publicado en Nature Mental Health, los adultos jóvenes que duermen menos de 6 horas elevan sus niveles de cortisol en un 37 % al día siguiente, lo que amplifica la percepción de estrés. Teniendo esto en cuenta, elabora una lista numerada de estrategias prácticas de autocuidado que reduzcan el estrés en adultos jóvenes.'
ws1['E25'] = 'Considera el siguiente dato reciente: según un estudio de 2023 publicado en Nature Mental Health, los adultos jóvenes que duermen menos de 6 horas elevan sus niveles de cortisol en un 37 % al día siguiente, lo que amplifica la percepción de estrés. Teniendo esto en cuenta, elabora una lista numerada de estrategias prácticas de autocuidado que reduzcan el estrés en adultos jóvenes. Responde como si fueras un psicólogo especializado en bienestar, con un tono empático y lenguaje claro.'

# Respuestas PE01
ws1['C27'] = '1. Establece una rutina de sueño regular (acostarte y levantarte a la misma hora). 2. Practica respiración diafragmática 5 min al despertar. 3. Haz actividad física moderada al menos 3 veces por semana. 4. Limita el uso de pantallas 1 hora antes de dormir. 5. Conecta con amigos o familiares al menos una vez por semana. 6. Dedica tiempo a una actividad que disfrutes sin culpa.'
ws1['D27'] = '1. Prioriza el sueño de 7-9 horas: dado que la privación de sueño eleva el cortisol un 37%, la primera estrategia es proteger tus horas de descanso con una rutina fija. 2. Practica higiene del sueño: evita pantallas, cafeína y ambientes ruidosos antes de acostarte. 3. Ejercicio regular: 30 min de actividad aeróbica moderada reduce la respuesta al estrés. 4. Técnicas de mindfulness: 10 min de meditación guiada al día regulan el eje HPA. 5. Alimentación antiinflamatoria: reduce azúcares procesados que elevan el cortisol. 6. Socialización activa: el apoyo social es un amortiguador fisiológico del estrés.'
ws1['E27'] = 'Como psicólogo especializado en bienestar, te recomiendo estas estrategias: 1. Recupera el sueño como prioridad clínica: ese 37% de aumento en cortisol no es trivial; dormir menos de 6 horas activa el eje hipotalámico-hipofisario-suprarrenal de forma crónica. 2. Respira antes de reaccionar: la respiración 4-7-8 activa el nervio vago y reduce la activación simpática. 3. Mueve tu cuerpo con intención: el ejercicio aeróbico libera endorfinas y reduce el cortisol basal. 4. Construye límites digitales: el scroll nocturno es un estímulo de alerta que sabotea el descanso. 5. Cultiva vínculos reales: la oxitocina del contacto social contrarresta el cortisol. 6. Practica la autocompasión: exigirte demasiado es una fuente de estrés crónico infravalorada.'

# Evaluación PE01
ws1['C33'] = 'Sí. Al pasar de la Versión 0 a la P, la respuesta dejó de ser genérica y comenzó a anclar cada estrategia en el dato del 37% de aumento de cortisol, lo que dio mayor coherencia interna y jerarquía a las recomendaciones (primero el sueño, luego las demás).'
ws1['C34'] = 'La Versión P lista estrategias bien fundamentadas pero mantiene un tono neutral y enciclopédico. La Versión R (con PE03) añade una voz clínica empática: usa primera persona del plural, explica el mecanismo detrás de cada recomendación y reconoce la dimensión emocional del estrés.'
ws1['C35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws1['C36'] = 'Al combinar información nueva (PE01) con un rol profesional (PE03), el modelo restringe su espacio generativo a la intersección de "datos de cortisol + perspectiva clínica empática". Esto reduce la varianza de la respuesta y la dirige hacia un registro más especializado y útil, coherente con la teoría de que los patrones de persona reducen la entropía distribucional del modelo al activar un subconjunto más acotado de su espacio latente.'

# ---- PE02 - FEW-SHOT ----
ws1['G23'] = '[--]'
ws1['H23'] = 'Usaremos PE02 para mostrar al modelo dos ejemplos del formato de respuesta deseado (estrategia + descripción + ejemplo práctico), de manera que replique esa estructura en todas las demás estrategias.'
ws1['I23'] = 'Usaremos PE02 + PE04 (Audiencia) porque al especificar ejemplos concretos Y el perfil del receptor (adulto joven universitario con poco tiempo), el modelo calibra mejor el tono y la complejidad de cada estrategia.'

ws1['G25'] = 'Dame una lista de estrategias prácticas de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['H25'] = 'Te mostraré el formato que necesito y luego tú completas el resto. Ejemplo 1 — Estrategia: Respiración diafragmática. Descripción: Inhala 4 segundos, retén 4, exhala 4. Activa el sistema nervioso parasimpático. Ejemplo práctico: Hazlo 3 veces antes de entrar a una reunión importante. Ejemplo 2 — Estrategia: Desconexión digital nocturna. Descripción: Evita pantallas 60 min antes de dormir para no elevar el cortisol. Ejemplo práctico: Cambia el teléfono por un libro físico o una conversación relajada. Siguiendo exactamente ese formato, dame 6 estrategias más.'
ws1['I25'] = 'Mi audiencia es un adulto joven universitario de 20-25 años, con agenda ajustada y poco tiempo libre. Te mostraré el formato que necesito y luego tú completas el resto. Ejemplo 1 — Estrategia: Respiración diafragmática. Descripción: Inhala 4 s, retén 4 s, exhala 4 s. Activa el sistema nervioso parasimpático. Ejemplo práctico: Hazlo 3 veces antes de entrar a un examen. Ejemplo 2 — Estrategia: Desconexión digital nocturna. Descripción: Evita pantallas 60 min antes de dormir. Ejemplo práctico: Pon el teléfono en otra habitación. Siguiendo exactamente ese formato, dame 6 estrategias más adaptadas a universitarios con poco tiempo.'

ws1['G27'] = '1. Respiración diafragmática — Inhala 4 s, retén 4 s, exhala 4 s; activa el parasimpático. Ejemplo: Antes de una reunión. 2. Desconexión digital nocturna — Apaga pantallas 60 min antes de dormir. Ejemplo: Lee un libro físico. [Continúa con 4 más en el mismo formato...]'
ws1['H27'] = '3. Ejercicio en micropausas — Descripción: 10 minutos de caminata rápida reducen el cortisol circulante. Ejemplo práctico: Da una vuelta a la manzana entre clases. 4. Journaling de gratitud — Descripción: Escribe 3 cosas positivas del día; reencuadra el sesgo negativo. Ejemplo práctico: Lleva una libreta pequeña o usa una nota en el teléfono. 5. Siesta de 20 minutos — Descripción: Mejora la consolidación de memoria y baja la irritabilidad. Ejemplo práctico: Pon una alarma y cierra las persianas. 6. Conexión social intencional — Descripción: Una llamada de 15 min con alguien de confianza libera oxitocina. Ejemplo práctico: Llama a un amigo mientras caminas. 7. Alimentación sin ultraprocesados — Descripción: Evita picos de glucosa que disparan el estrés metabólico. Ejemplo práctico: Sustituye las galletas por fruta y nueces. 8. Rutina de cierre del día — Descripción: Escribe 3 pendientes para mañana y cierra el portátil. Ejemplo práctico: Hazlo siempre a la misma hora para señalizar al cerebro el fin del día laboral.'
ws1['I27'] = '3. Micropausas activas — Descripción: 10 min de caminata entre clases bajan el cortisol sin quitarte tiempo de estudio. Ejemplo práctico: Camina al baño más lejano o sube escaleras. 4. Journaling exprés — Descripción: 5 min escribiendo 3 cosas buenas del día reencuadra el sesgo negativo del cerebro estudiantil. Ejemplo práctico: Hazlo mientras esperas el bus. 5. Siesta de 20 min — Descripción: Recupera el rendimiento cognitivo en mitad de una jornada larga. Ejemplo práctico: Pon alarma para no pasarte; un banco de la facultad funciona. 6. Conexión real breve — Descripción: Una llamada corta con alguien de confianza libera oxitocina anti-estrés. Ejemplo práctico: Llama a casa mientras almuerzas. 7. Comida sin pantallas — Descripción: Comer con atención plena reduce el estrés digestivo y mejora la saciedad. Ejemplo práctico: Deja el teléfono bocabajo durante el almuerzo. 8. Ritual de cierre nocturno — Descripción: Escribe 3 pendientes de mañana antes de cerrar el portátil; vacía la mente. Ejemplo práctico: Hazlo siempre a la misma hora para señalizar el fin del día.'

ws1['G33'] = 'Sí. La Versión P introdujo estructura consistente (estrategia + descripción + ejemplo práctico), lo que hizo la información más escaneable y aplicable que el listado plano de la V0.'
ws1['G34'] = 'La Versión P ya tenía la estructura, pero era genérica. La Versión R (con PE04) adaptó el lenguaje, los ejemplos y la escala de tiempo al perfil universitario: las estrategias caben en una agenda ajustada y los ejemplos son situaciones reales del campus.'
ws1['G35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws1['G36'] = 'PE02 ya reducía el espacio generativo al fijar un formato. PE04 lo redujo aún más al definir al receptor: el modelo activó representaciones asociadas a "universitario joven con poco tiempo", filtrando estrategias largas o costosas y privilegiando las de bajo coste temporal. Según la teoría de condicionamiento del espacio de búsqueda, cada restricción adicional (formato + audiencia) multiplica el efecto de acotamiento, produciendo respuestas más precisas.'

# ---- PE03 - ASUMIR PERSONA ----
ws1['K23'] = '[--]'
ws1['L23'] = 'Usaremos PE03 para pedirle al modelo que asuma el rol de un coach de bienestar certificado, lo que orienta el tono, el vocabulario y el nivel de profundidad de las recomendaciones.'
ws1['M23'] = 'Usaremos PE03 + PE01 (Información Nueva) porque el rol de coach junto con un dato científico reciente lleva la respuesta de lo meramente motivacional a lo clínicamente fundamentado.'

ws1['K25'] = 'Dame una lista de estrategias prácticas de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['L25'] = 'Actúa como un coach de bienestar certificado con 10 años de experiencia trabajando con adultos jóvenes. Desde ese rol, elabora una lista de estrategias prácticas de autocuidado para reducir el estrés, explicando brevemente el mecanismo detrás de cada una.'
ws1['M25'] = 'Actúa como un coach de bienestar certificado con 10 años de experiencia trabajando con adultos jóvenes. Incorpora el siguiente dato en tu respuesta: según un metaanálisis de 2023 (Lancet Psychiatry), las intervenciones de mindfulness reducen los síntomas de estrés crónico en un 43% en adultos de 18-30 años. Desde ese rol y con ese dato en mente, elabora una lista de estrategias prácticas de autocuidado para reducir el estrés, explicando el mecanismo detrás de cada una.'

ws1['K27'] = 'Como coach de bienestar, te recomiendo: 1. Respiración consciente (activa el nervio vago, frena la respuesta de lucha-huida). 2. Movimiento diario (libera BDNF, que repara sinapsis dañadas por el cortisol). 3. Sueño prioritario (consolida aprendizajes y baja la reactividad emocional). 4. Alimentación antiinflamatoria (reduce interleucinas proinflamatorias asociadas al estrés). 5. Límites digitales (evita la sobre-estimulación dopaminérgica nocturna). 6. Conexión social genuina (la oxitocina bloquea parcialmente el cortisol).'
ws1['L27'] = 'Como coach de bienestar con una década de práctica, he visto que estas estrategias son las más efectivas: 1. Mindfulness estructurado (10 min/día): activa la corteza prefrontal y regula la amígdala, reduciendo la reactividad emocional. 2. Ejercicio aeróbico (30 min, 3x semana): la liberación de BDNF contrarresta el daño neuronal del cortisol crónico. 3. Higiene del sueño estricta: la privación de sueño es la palanca más rápida para disparar el estrés. 4. Journaling de preocupaciones: externalizar los pensamientos rumiativos reduce la carga de la memoria de trabajo. 5. Alimentación rica en triptófano: precursor de la serotonina, el neurotransmisor del bienestar. 6. Socialización de calidad: los vínculos seguros son el mejor regulador del sistema nervioso autónomo.'
ws1['M27'] = 'Como coach de bienestar con 10 años de experiencia, y a la luz del metaanálisis de Lancet Psychiatry que confirma una reducción del 43% en estrés crónico con mindfulness en jóvenes de 18-30 años, mis recomendaciones principales son: 1. Mindfulness diario (10-20 min): es la intervención con mayor respaldo empírico; activa la corteza prefrontal y reduce la reactividad de la amígdala. 2. Ejercicio aeróbico regular: libera BDNF y endorfinas, compensando el daño del cortisol crónico. 3. Sueño de calidad (7-9 h): la base fisiológica de toda recuperación; sin él, ninguna otra estrategia funciona al máximo. 4. Límites digitales: la sobreestimulación de dopamina por redes sociales mantiene el sistema nervioso en alerta. 5. Nutrición antiinflamatoria: los ultraprocesados elevan marcadores de inflamación asociados al estrés. 6. Red de apoyo activa: el contacto humano genuino libera oxitocina, que antagoniza el cortisol.'

ws1['K33'] = 'Sí. La V0 era una lista neutral y sin jerarquía. La VP adoptó un tono de experto con autoridad profesional, explicó mecanismos fisiológicos detrás de cada estrategia y utilizó un lenguaje más preciso y motivador.'
ws1['K34'] = 'La VP tenía el rol pero sin datos externos. La VR integró el metaanálisis del Lancet, lo que elevó la credibilidad científica de las recomendaciones y jerarquizó el mindfulness como la estrategia de mayor evidencia, algo que la VP no hacía explícitamente.'
ws1['K35'] = 'Diferencia en los datos de entrenamiento'
ws1['K36'] = 'La adición del dato del metaanálisis de Lancet Psychiatry funcionó como "anclaje evidencial": el modelo no podía ignorarlo al generar la respuesta, ya que los datos de entrenamiento de Claude incluyen el aprendizaje de que citar evidencia de alto impacto (Lancet) obliga a priorizar la estrategia mencionada en el texto. El resultado es una respuesta jerarquizada según evidencia, no solo según intuición del coach.'

# ---- PE04 - AUDIENCIA ----
ws1['O23'] = '[--]'
ws1['P23'] = 'Usaremos PE04 para definir con precisión a quién va dirigida la respuesta: adultos jóvenes universitarios de 20-25 años, con carga académica alta y poco tiempo libre, para que el modelo adapte el registro y la practicidad.'
ws1['Q23'] = 'Usaremos PE04 + PE02 (Few-Shot) porque al combinar audiencia definida con ejemplos del formato deseado, el modelo genera estrategias que son a la vez adecuadas para ese perfil Y presentadas en la estructura más útil.'

ws1['O25'] = 'Dame una lista de estrategias prácticas de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['P25'] = 'La siguiente respuesta va dirigida a adultos jóvenes de 20-25 años que estudian en la universidad, tienen una carga académica alta, poco tiempo libre y acceso limitado a recursos económicos. Teniendo en cuenta ese perfil, elabora una lista de estrategias prácticas de autocuidado para reducir el estrés que sean aplicables en menos de 15 minutos y sin costo.'
ws1['Q25'] = 'La siguiente respuesta va dirigida a adultos jóvenes de 20-25 años que estudian en la universidad, tienen alta carga académica y poco tiempo libre. Te mostraré el formato deseado. Ejemplo: Estrategia: Respiración 4-4-4. Tiempo: 3 min. Cuándo aplicarla: antes de un examen. Siguiendo ese formato, dame 7 estrategias más que no tomen más de 15 minutos y sean gratuitas.'

ws1['O27'] = '1. Respira profundo varias veces cuando sientas tensión. 2. Sal a caminar aunque sea 10 minutos. 3. Escucha música que te relaje. 4. Habla con un amigo. 5. Duerme las horas necesarias. 6. Come bien y evita el café en exceso. 7. Haz pausas durante el estudio.'
ws1['P27'] = '1. Respiración 4-4-4: inhala 4 s, retén 4 s, exhala 4 s — 3 min, gratis, hazlo entre clases. 2. Caminata corta: 10 min al aire libre bajan el cortisol y despejan la mente — sin costo, entre bloques de estudio. 3. Journaling de 5 min: escribe lo que te preocupa para vaciarlo de la cabeza — solo necesitas papel. 4. Siesta de 20 min: recupera el rendimiento en mitad de jornada larga — pon alarma para no pasarte. 5. Llamada breve a alguien de confianza: 10 min de conversación real liberan oxitocina. 6. Estiramiento de silla: 5 min de movilidad articular en la silla de estudio reducen la tensión muscular. 7. Técnica Pomodoro: 25 min de foco + 5 de pausa evita la fatiga acumulada.'
ws1['Q27'] = '1. Respiración 4-4-4. Tiempo: 3 min. Cuándo: antes de un examen o reunión importante. 2. Caminata entre clases. Tiempo: 10 min. Cuándo: entre bloques de estudio, preferiblemente al aire libre. 3. Journaling de descarga. Tiempo: 5 min. Cuándo: al llegar a casa, antes de abrir redes sociales. 4. Siesta de recuperación. Tiempo: 20 min. Cuándo: después del almuerzo si hubo mala noche. 5. Estiramiento de silla. Tiempo: 5 min. Cuándo: cada 90 min de estudio. 6. Llamada a alguien de confianza. Tiempo: 10 min. Cuándo: en el bus o caminando de regreso. 7. Técnica Pomodoro. Tiempo: ciclos de 30 min. Cuándo: durante sesiones largas de estudio para evitar fatiga acumulada.'

ws1['O33'] = 'Sí. La V0 ofrecía consejos genéricos aplicables a cualquier persona. La VP filtró las estrategias por dos criterios clave del perfil (tiempo ≤15 min y costo cero), eliminando opciones como yoga en estudio o terapia, que son inaccesibles para ese público.'
ws1['O34'] = 'La VP filtraba por tiempo y costo pero presentaba las estrategias en formato de párrafo corrido. La VR (con PE02) estructuró la información en tres campos escaneables por ítem (estrategia, tiempo, cuándo), lo que la hace más usable como guía de referencia rápida.'
ws1['O35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws1['O36'] = 'Cada restricción añadida (perfil de audiencia + formato few-shot) actúa como un filtro que reduce el espacio de posibles respuestas del modelo. La audiencia elimina estrategias costosas o lentas; el few-shot fija la estructura de salida. La combinación produce una respuesta de mayor densidad informativa por línea, lo que es coherente con la teoría de que restricciones múltiples y compatibles se amplifican mutuamente al dirigir la atención del modelo hacia un subespacio muy acotado del texto posible.'

# ---- PE05 - AFINAMIENTO DE PREGUNTAS ----
ws1['S23'] = '[--]'
ws1['T23'] = 'Usaremos PE05 para pedirle al modelo que antes de responder nos haga las preguntas necesarias para entender mejor el contexto y personalizar las estrategias de autocuidado.'
ws1['U23'] = 'Usaremos PE05 + PE03 (Persona) porque al combinar el afinamiento de contexto con el rol de coach, el modelo no solo pregunta lo correcto, sino que interpreta las respuestas desde un marco profesional de bienestar.'

ws1['S25'] = 'Dame una lista de estrategias prácticas de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['T25'] = 'Quiero que me des estrategias de autocuidado para reducir el estrés. Pero antes de responder, hazme las preguntas que necesites para entender mejor mi situación y poder personalizar las recomendaciones. Una vez que yo responda, elabora la lista adaptada a mi perfil.'
ws1['U25'] = 'Actúa como un coach de bienestar certificado. Antes de darme estrategias de autocuidado para reducir el estrés, hazme las preguntas que necesites para entender mi perfil (rutina, fuentes de estrés, tiempo disponible, recursos). Una vez que yo responda, elabora una lista personalizada.'

ws1['S27'] = '1. Establece una rutina de sueño fija. 2. Haz ejercicio 3 veces por semana. 3. Practica meditación 10 min al día. 4. Limita el uso de redes sociales. 5. Conecta con personas cercanas. 6. Lleva una alimentación equilibrada. 7. Haz actividades que disfrutes.'
ws1['T27'] = 'Antes de darte recomendaciones personalizadas, necesito entenderte mejor. ¿Cuáles son tus principales fuentes de estrés actualmente (trabajo, estudios, relaciones, económicas)? ¿Cuánto tiempo libre tienes al día en promedio? ¿Tienes alguna práctica de autocuidado que ya hayas intentado? ¿Hay limitaciones físicas, económicas o de tiempo que deba considerar? ¿Prefieres estrategias individuales o que puedan hacerse en grupo?'
ws1['U27'] = 'Como coach de bienestar, antes de recomendarte nada necesito conocerte mejor. Cuéntame: ¿cuál es tu mayor fuente de estrés en este momento (académica, laboral, relacional)? ¿Cuántas horas libres tienes al día? ¿Has intentado alguna técnica de manejo de estrés antes? ¿Qué funcionó y qué no? ¿Tienes acceso a espacios al aire libre o instalaciones deportivas? Con esas respuestas podré diseñarte un plan realmente adaptado a ti.'

# Prompt de consecucion PE05 (el patron requiere ida y vuelta)
ws1['T29'] = 'Mis principales fuentes de estrés son los exámenes y los trabajos en grupo. Tengo aproximadamente 1 hora libre al día, generalmente por la noche. He intentado meditar pero me cuesta concentrarme. No tengo limitaciones físicas ni económicas importantes. Prefiero estrategias individuales que pueda hacer solo.'
ws1['U29'] = 'Mis principales fuentes de estrés son los exámenes y los plazos de entrega. Tengo 1 hora libre al día, por las noches. He intentado la meditación pero no logro mantener la atención más de 5 minutos. Tengo acceso a un parque cercano y al gimnasio de la universidad.'

ws1['T31'] = '1. Respiración 4-7-8 antes de dormir (resuelve el problema de concentración inicial). 2. Journaling de descarga antes de acostarte: escribe pendientes del día siguiente para vaciar la mente. 3. Caminata de 15 min después de cenar: reduce el cortisol acumulado del día. 4. Técnica Pomodoro durante el estudio: 25 min foco + 5 pausa para evitar la saturación cognitiva. 5. Escucha de música instrumental mientras estudias: reduce la ansiedad sin distraer. 6. Prepara el entorno de estudio la noche anterior: reduce la incertidumbre matutina.'
ws1['U31'] = 'Dado tu perfil (estrés académico, 1 h libre nocturna, dificultad con meditación formal), te recomiendo: 1. Meditación en movimiento: camina 20 min en el parque con auriculares y una guía de mindfulness; resuelve tu dificultad con la meditación estática. 2. Journaling de 5 min antes de cerrar el portátil: externaliza los pendientes para no rumiarlos al dormir. 3. Sesión de gimnasio de 30 min, 3x semana: el ejercicio es la intervención anti-estrés más respaldada para tu perfil. 4. Técnica Pomodoro en las tardes de estudio: estructura el tiempo y previene la fatiga cognitiva. 5. Respiración 4-4-4 antes de cada examen: portable y discreta. 6. Ritual de cierre nocturno: a la misma hora, misma secuencia (ducha, lectura, luces apagadas).'

ws1['S33'] = 'Sí. La V0 producía consejos genéricos. La VP transformó la interacción en un diálogo: el modelo identificó variables clave del usuario (fuentes de estrés, tiempo, experiencia previa) antes de recomendar, lo que garantiza que la lista final sea relevante.'
ws1['S34'] = 'La VP hacía buenas preguntas pero desde un tono neutral. La VR (con PE03) reformuló las preguntas desde el marco de un coach: preguntó por intentos previos y por qué no funcionaron, lo que añadió una dimensión metacognitiva y permitió una personalización más profunda en la fase final.'
ws1['S35'] = 'Diferencia según la UI programada'
ws1['S36'] = 'El patrón de afinamiento de preguntas activa un modo de interacción multi-turno que no todos los chatbots gestionan igual. Claude está optimizado para conversaciones de ida y vuelta con memoria de contexto dentro del hilo, lo que le permite integrar las respuestas del usuario en la generación final sin perder coherencia. Esto se debe en parte a decisiones de diseño de la UI (contexto de hilo largo) y en parte al ajuste fino del modelo para seguir instrucciones de espera antes de responder.'

# ---- PE06 - ALTERNATIVAS ----
ws1['W23'] = '[--]'
ws1['X23'] = 'Usaremos PE06 para pedirle al modelo que genere varias versiones alternativas del mismo consejo, diferenciadas por perfil de usuario, de modo que el lector pueda elegir la que mejor se adapte a su situación.'
ws1['Y23'] = 'Usaremos PE06 + PE11 (Template, de estructura) combinados: pediremos alternativas Y que cada una siga una plantilla fija, asegurando consistencia comparativa entre opciones.'

ws1['W25'] = 'Dame una lista de estrategias prácticas de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['X25'] = 'Dame tres versiones alternativas de una guía de autocuidado para reducir el estrés en adultos jóvenes: una para alguien con muy poco tiempo (menos de 10 min al día), otra para alguien con tiempo moderado (30 min al día) y otra para alguien con tiempo amplio (más de 1 hora al día). Cada versión debe tener exactamente 5 estrategias.'
ws1['Y25'] = 'Dame tres versiones alternativas de una guía de autocuidado para reducir el estrés en adultos jóvenes. Perfil A: menos de 10 min/día. Perfil B: 30 min/día. Perfil C: más de 1 hora/día. Cada estrategia debe seguir esta plantilla: Nombre | Tiempo | Mecanismo | Cuándo aplicarla.'

ws1['W27'] = '1. Respira profundo. 2. Sal a caminar. 3. Escucha música relajante. 4. Habla con alguien. 5. Duerme bien. 6. Come sano. 7. Haz ejercicio. 8. Medita. 9. Limita las pantallas. 10. Practica hobbies.'
ws1['X27'] = 'VERSIÓN A (<10 min/día): 1. Respiración 4-4-4 (3 min). 2. Estiramiento de silla (2 min). 3. Texto de gratitud a un amigo (1 min). 4. Agua fría en muñecas para bajar activación (30 s). 5. Pausa sin pantalla entre tareas (2 min). — VERSIÓN B (30 min/día): 1. Caminata consciente (15 min). 2. Journaling de cierre del día (5 min). 3. Meditación guiada (10 min). 4. Estiramiento suave (5 min). 5. Llamada breve a alguien de confianza (10 min). — VERSIÓN C (+1 hora/día): 1. Sesión de ejercicio aeróbico (45 min). 2. Meditación de escaneo corporal (20 min). 3. Cocinar una comida saludable (30 min). 4. Lectura de ficción (30 min). 5. Socialización presencial (60 min o más).'
ws1['Y27'] = 'VERSIÓN A (<10 min): 1. Respiración 4-4-4 | 3 min | Activa el nervio vago | Antes de cualquier momento de tensión. 2. Estiramiento de silla | 2 min | Libera tensión muscular acumulada | Cada 90 min de estudio. 3. Mensaje de gratitud | 1 min | Activa circuitos de recompensa social | Al mediodía. 4. Agua fría en muñecas | 30 s | Reduce la activación simpática rápidamente | En crisis de ansiedad leve. 5. Pausa sin pantalla | 2 min | Permite reset atencional | Entre tareas. — VERSIÓN B (30 min): 1. Caminata consciente | 15 min | Reduce cortisol y activa endorfinas | Después del almuerzo. 2. Journaling | 5 min | Externaliza la rumiación | Antes de dormir. 3. Meditación guiada | 10 min | Regula la amígdala | Al despertar. 4. Música sin letra | 5 min | Reduce arousal cognitivo | Al inicio del estudio. 5. Llamada breve | 10 min | Libera oxitocina | En la tarde. — VERSIÓN C (+1 h): [idem extendido con deporte, cocina saludable, lectura y socialización presencial].'

ws1['W33'] = 'Sí. La V0 generó una lista única no segmentada. La VP introdujo tres versiones diferenciadas por disponibilidad de tiempo, lo que hace la respuesta inmediatamente accionable porque el usuario puede identificar su perfil y aplicar la versión que le corresponde.'
ws1['W34'] = 'La VP diferenciaba por tiempo pero no estandarizaba la presentación de cada ítem. La VR añadió la plantilla (nombre, tiempo, mecanismo, cuándo), lo que facilita la comparación directa entre estrategias y entre versiones.'
ws1['W35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws1['W36'] = 'La plantilla (PE11) funciona como una restricción estructural que, combinada con las tres audiencias (PE06), reduce drásticamente el espacio generativo: el modelo no puede producir texto libre, sino que debe rellenar cuatro campos fijos por estrategia. Esto activa el modo de generación "fill-in-the-blank", que en los modelos de lenguaje tiende a producir respuestas más densas y precisas porque cada token debe cumplir una función predefinida.'

# ---- PE07 - INTERACCIÓN INVERTIDA ----
ws1['AA23'] = '[--]'
ws1['AB23'] = 'Usaremos PE07 para invertir los roles: le pediremos al modelo que sea él quien haga las preguntas para diagnosticar nuestro nivel de estrés, y nosotros responderemos para luego recibir un plan personalizado.'
ws1['AC23'] = 'Usaremos PE07 + PE03 (Persona) porque la inversión de roles funciona mejor cuando el modelo adopta un rol definido (terapeuta de bienestar) que le da un marco claro para formular las preguntas correctas.'

ws1['AA25'] = 'Dame una lista de estrategias prácticas de autocuidado para reducir el estrés en adultos jóvenes.'
ws1['AB25'] = 'Quiero mejorar mi manejo del estrés. En lugar de que yo te haga preguntas, quiero que tú me hagas preguntas para diagnosticar mi situación. Hazme una pregunta a la vez. Cuando hayas reunido suficiente información, elabora un plan de autocuidado personalizado para mí.'
ws1['AC25'] = 'Actúa como un terapeuta de bienestar. Quiero mejorar mi manejo del estrés. En lugar de que yo te explique todo de golpe, tú guía la conversación: hazme una pregunta a la vez para entender mi situación. Cuando tengas suficiente información (máximo 5 preguntas), elabora un plan personalizado.'

ws1['AA27'] = '1. Respira profundo al sentir estrés. 2. Haz ejercicio con regularidad. 3. Duerme las horas necesarias. 4. Habla de tus problemas con alguien de confianza. 5. Reduce el consumo de cafeína. 6. Organiza tu tiempo con listas de tareas. 7. Desconéctate de las pantallas antes de dormir.'
ws1['AB27'] = '¿Cuál dirías que es tu principal fuente de estrés en este momento: el trabajo/estudios, las relaciones personales, la economía, o algo más?'
ws1['AC27'] = 'Como terapeuta de bienestar, antes de darte un plan necesito conocerte. Empecemos por aquí: ¿en qué área de tu vida sientes que el estrés te afecta más: lo académico/laboral, lo relacional o lo personal (salud, autoimagen, propósito)?'

# Prompt de consecucion PE07 (interaccion invertida requiere multiples turnos)
ws1['AB29'] = 'Mi principal fuente de estrés son los estudios, especialmente los exámenes y los trabajos grupales. También siento presión por el tiempo porque trabajo medio tiempo además de estudiar.'
ws1['AC29'] = 'Lo que más me afecta es lo académico-laboral: estoy estudiando y trabajando al mismo tiempo, y siento que nunca tengo suficiente tiempo ni energía para todo.'

ws1['AB31'] = 'Entiendo, la combinación de estudio y trabajo es muy exigente. Algunas preguntas más: ¿cuántas horas duermes en promedio? ¿Tienes algún momento del día que sientas tuyo, sin obligaciones? ¿Has probado antes alguna técnica de manejo del estrés? Plan personalizado: Dado que trabajas y estudias y el tiempo es tu recurso más escaso, te propongo: 1. Micro-respiraciones (3 min) entre el trabajo y los estudios para hacer transición mental. 2. Técnica Pomodoro estricta (25+5) para maximizar el estudio sin agotarte. 3. Una sola actividad de cierre nocturno (journaling o lectura 10 min) para desconectar. 4. Bloque de sueño no negociable de 7 h. 5. Un momento social semanal de al menos 1 h sin hablar de trabajo ni estudio.'
ws1['AC31'] = 'Gracias por compartirlo. La doble carga académica y laboral es uno de los contextos de mayor estrés crónico en adultos jóvenes. Siguiente pregunta: ¿cuántas horas duermes en un día laboral típico? Plan personalizado (tras 3 preguntas): Dado tu contexto, el plan se centra en maximizar la recuperación con el tiempo mínimo disponible: 1. Transición trabajo-estudio con 5 min de respiración consciente. 2. Pomodoro 25+5 para estudiar sin acumular fatiga cognitiva. 3. Journaling de 5 min antes de dormir para vaciar la mente. 4. Siesta de 20 min en días de jornada doble. 5. Un bloque semanal de desconexión total (mínimo 2 h sin compromisos).'

ws1['AA33'] = 'Sí. La V0 daba consejos impersonales. La VP transformó la interacción en un proceso diagnóstico donde el modelo tomó la iniciativa, lo que redujo la carga cognitiva del usuario y generó un plan más relevante porque se basó en información real del usuario.'
ws1['AA34'] = 'La VP hacía preguntas útiles pero sin un rol claro. La VR (con PE03) adoptó el marco de un terapeuta, lo que cambió el tipo de preguntas formuladas: más abiertas, orientadas a comprender causas raíz en lugar de solo síntomas, y el plan final fue más integral y estructurado.'
ws1['AA35'] = 'Diferencia según la UI programada'
ws1['AA36'] = 'El patrón de interacción invertida depende críticamente de la capacidad del modelo de mantener el contexto conversacional a lo largo de múltiples turnos. Claude mantiene toda la conversación en su ventana de contexto, lo que le permite integrar todas las respuestas anteriores del usuario al elaborar el plan final. Modelos con ventanas de contexto más cortas o interfaces que no preservan el hilo completo producirían planes menos coherentes con el historial del usuario.'

# =============================================
# HOJA 2: Patrones de estructura
# =============================================
ws2 = wb['Patrones de estructura']

# Caso de uso / consulta base
ws2['C8'] = 'Educación y aprendizaje'
ws2['C9'] = 'Diseño de materiales didácticos para enseñar programación básica a principiantes.'
ws2['C10'] = 'Elaborar un conjunto de recursos didácticos que un docente pueda usar para introducir los conceptos básicos de programación a estudiantes sin experiencia previa.'
ws2['C12'] = 'Recursos organizados por tipo (explicación, ejercicio, ejemplo, checklist). Cada recurso en sección separada con título claro.'
ws2['C13'] = 'Lenguaje simple, ejemplos del mundo real, sin tecnicismos innecesarios. Adaptado a principiantes absolutos.'
ws2['C14'] = 'Variables, condicionales, bucles, funciones. Analogías cotidianas. Errores comunes de principiantes.'
ws2['C15'] = 'No uses pseudocódigo complejo ni referencias a lenguajes específicos avanzados. No asumas conocimientos previos. No menciones la tarea encomendada en tu respuesta.'

for col in ['C', 'G', 'K', 'O', 'S', 'W', 'AA', 'AE']:
    ws2[f'{col}21'] = 'Claude'

# ---- PE08 - VERIFICACIÓN COGNITIVA ----
ws2['C23'] = '[--]'
ws2['D23'] = 'Usaremos PE08 para pedirle al modelo que antes de generar el material didáctico, identifique y declare los supuestos que está asumiendo sobre el nivel del estudiante, así como los posibles puntos de confusión.'
ws2['E23'] = 'Usaremos PE08 + PE09 (Cadena de Pensamiento) porque al combinar la verificación de supuestos con el razonamiento paso a paso, el modelo produce materiales que no solo son correctos sino que siguen una progresión pedagógica coherente.'

ws2['C25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['D25'] = 'Antes de crear los materiales didácticos para enseñar programación básica, identifica y declara: (1) qué supuestos estás asumiendo sobre el nivel del estudiante, (2) cuáles son los conceptos previos necesarios, y (3) cuáles son los 3 puntos de mayor confusión potencial. Luego, crea los materiales teniendo en cuenta esas consideraciones.'
ws2['E25'] = 'Antes de crear los materiales, razona paso a paso: ¿qué sabe un principiante absoluto? ¿Qué no sabe? ¿Cuál es la secuencia lógica para introducir los conceptos? ¿Dónde suelen perderse los estudiantes? Muestra ese razonamiento explícitamente antes de generar el material. Luego crea los materiales siguiendo esa lógica.'

ws2['C27'] = 'Variables: son como cajas donde guardas información. Condicionales: si pasa X, haz Y. Bucles: repite algo varias veces. Funciones: agrupa instrucciones para reutilizarlas. Ejercicios: nombra 5 variables para guardar tu nombre, edad, ciudad, altura y color favorito.'
ws2['D27'] = 'Supuestos asumidos: el estudiante no tiene experiencia previa con código, sí usa computadora con frecuencia, y aprende mejor con analogías cotidianas. Conocimientos previos necesarios: ninguno técnico; solo saber usar un teclado. Puntos de mayor confusión: (1) diferencia entre = (asignación) y == (comparación), (2) indentación como parte de la sintaxis, (3) por qué los bucles pueden ser infinitos. Materiales: [Módulo 1 - Variables: analogía de la caja etiquetada, ejercicio de nombrar 5 variables, error común: nombres con espacios] [Módulo 2 - Condicionales: analogía del semáforo, ejercicio de if/else en pseudocódigo, error común: olvidar el else] [Módulo 3 - Bucles: analogía de la lista de tareas repetida, ejercicio de contador, error común: bucle infinito]'
ws2['E27'] = 'Razonamiento paso a paso: Un principiante absoluto sabe usar apps pero no tiene modelo mental del código. Lo primero que necesita es entender que el código es una secuencia de instrucciones, como una receta. La secuencia lógica es: variables → condicionales → bucles → funciones. Los puntos de pérdida más frecuentes son la indentación (invisible pero funcional) y la diferencia entre = y ==. Materiales generados siguiendo esa lógica: [Módulo 0: ¿Qué es programar? Analogía de la receta de cocina] [Módulo 1 - Variables: analogía de la etiqueta del frasco] [Módulo 2 - Condicionales: analogía del semáforo] [Módulo 3 - Bucles: analogía del reproductor de música en modo repeat] [Módulo 4 - Funciones: analogía del botón de microondas con programa guardado]'

ws2['C33'] = 'Sí. La V0 generó materiales correctos pero sin conciencia de los puntos débiles. La VP declaró explícitamente los supuestos y los errores comunes antes de generar el material, lo que produjo un módulo "de vacunación" para cada error frecuente, ausente en la V0.'
ws2['C34'] = 'La VP producía materiales con secciones de error común, pero el razonamiento estaba implícito. La VR mostró el razonamiento pedagógico explícitamente antes del material, lo que permite al docente entender la lógica de diseño y adaptarla; además, añadió un Módulo 0 de introducción conceptual que la VP omitía.'
ws2['C35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws2['C36'] = 'La verificación cognitiva (PE08) fuerza al modelo a activar su "metarepresentación" del conocimiento del usuario antes de generar contenido. La cadena de pensamiento (PE09) hace visible ese proceso. Juntos, reducen el espacio generativo al subespacio de respuestas pedagógicamente secuenciadas, eliminando el riesgo de que el modelo salte a conceptos avanzados prematuramente, algo habitual cuando no se le obliga a razonar explícitamente sobre el nivel del aprendiz.'

# ---- PE09 - CADENA DE PENSAMIENTO ----
ws2['G23'] = '[--]'
ws2['H23'] = 'Usaremos PE09 para pedirle al modelo que razone paso a paso antes de generar cada material didáctico, mostrando su proceso de diseño pedagógico de forma explícita.'
ws2['I23'] = 'Usaremos PE09 + PE13 (Checklist) porque al combinar el razonamiento explícito con una lista de verificación al final de cada módulo, el docente puede seguir el hilo de diseño Y verificar que el material cumple todos los criterios de calidad.'

ws2['G25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['H25'] = 'Para crear materiales didácticos sobre programación básica para principiantes, razona paso a paso: primero identifica los conceptos clave, luego determina el orden pedagógico óptimo, después diseña una analogía cotidiana para cada concepto, y finalmente crea el material. Muestra cada paso de tu razonamiento antes de presentar el material final.'
ws2['I25'] = 'Para crear materiales didácticos sobre programación básica para principiantes, razona paso a paso: identifica conceptos, determina orden pedagógico, diseña analogías. Luego crea el material. Al final de cada módulo, incluye una checklist para que el docente verifique: ¿el concepto tiene analogía? ¿hay un ejercicio? ¿se menciona el error más común? ¿hay criterio de éxito claro?'

ws2['G27'] = 'Paso 1 - Conceptos clave: variables, condicionales, bucles, funciones. Paso 2 - Orden pedagógico: variables primero (base de todo), luego condicionales (lógica), luego bucles (repetición), finalmente funciones (abstracción). Paso 3 - Analogías: variable=caja etiquetada, condicional=semáforo, bucle=lista de reproducción en repeat, función=botón de microondas preprogramado. Material: [Módulo 1: Variables...] [Módulo 2: Condicionales...] [Módulo 3: Bucles...] [Módulo 4: Funciones...]'
ws2['H27'] = 'Razonamiento: Los principiantes necesitan anclajes cognitivos antes de la abstracción. El orden variables→condicionales→bucles→funciones respeta la dependencia conceptual: no puedes entender un bucle si no entiendes una variable. Las analogías deben ser del mundo cotidiano del estudiante joven (apps, música, cocina). Material: [Módulo 1: Variables como cajas etiquetadas | Ejercicio: crea 5 variables | Error común: nombre con espacios] [Módulo 2: Condicionales como semáforo | Ejercicio: if/else de temperatura | Error: olvidar elif] [Módulo 3: Bucles como playlist en repeat | Ejercicio: contador del 1 al 10 | Error: bucle infinito] [Módulo 4: Funciones como recetas guardadas | Ejercicio: función saludar(nombre) | Error: no llamar a la función]'
ws2['I27'] = 'Razonamiento: [mismo proceso explícito] Material con checklists integradas: Módulo 1 - Variables: [contenido] ✅ Checklist docente: ¿Usaste la analogía de la caja? ¿El ejercicio pide crear al menos 3 variables? ¿Mencionaste el error de nombres con espacios? ¿El criterio de éxito es que el estudiante pueda nombrar y asignar una variable sin ayuda? — Módulo 2 - Condicionales: [contenido] ✅ Checklist: ¿Usaste una analogía de decisión cotidiana? ¿El ejercicio tiene al menos un caso verdadero y uno falso? ¿Abordaste el error de = vs ==? ¿El criterio es escribir un if/else correcto? — [igual para módulos 3 y 4]'

ws2['G33'] = 'Sí. La V0 producía materiales correctos pero sin justificación de por qué estaban ordenados así ni por qué se elegían esas analogías. La VP mostró el proceso de diseño, lo que hace el material más comprensible para el docente y más fácil de adaptar.'
ws2['G34'] = 'La VP mostraba el razonamiento pero los módulos no tenían criterios de verificación. La VR añadió una checklist al final de cada módulo, lo que convierte el material de "contenido para presentar" en "material con control de calidad integrado".'
ws2['G35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws2['G36'] = 'La cadena de pensamiento (PE09) reduce el espacio generativo al forzar al modelo a generar tokens de razonamiento antes de los tokens de contenido. Esto activa representaciones de diseño pedagógico que normalmente están implícitas. Al añadir la checklist (PE13), se añade una restricción adicional de formato al final de cada módulo, lo que garantiza que el modelo no omita ningún componente pedagógico clave.'

# ---- PE10 - FILTRO SEMÁNTICO ----
ws2['K23'] = '[--]'
ws2['L23'] = 'Usaremos PE10 para pedirle al modelo que filtre el contenido generado según criterios semánticos específicos: solo incluir estrategias que sean aplicables sin experiencia previa y que no requieran instalación de software.'
ws2['M23'] = 'Usaremos PE10 + PE08 (Verificación Cognitiva) porque filtrar el contenido Y verificar supuestos previos asegura que los materiales pasen dos controles de calidad: relevancia para principiantes y coherencia pedagógica.'

ws2['K25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['L25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes. Al generar el contenido, aplica el siguiente filtro: incluye solo explicaciones que no requieran conocimientos previos de matemáticas avanzadas, solo ejercicios que puedan hacerse con papel y lápiz o en un editor de texto simple, y excluye cualquier referencia a configuración de entornos o instalación de software.'
ws2['M25'] = 'Antes de generar el material, verifica estos supuestos: ¿el estudiante sabe qué es una variable en matemáticas? (asume que no). ¿Tiene un editor de código instalado? (asume que no, usa solo pseudocódigo o Python online). ¿Ha visto alguna vez un error de compilación? (asume que no). Luego crea los materiales aplicando el filtro: solo incluye contenido aplicable desde cero, sin instalaciones, sin jerga técnica.'

ws2['K27'] = 'Módulo 1 - Variables: una variable es un nombre que le das a un dato para recordarlo. Como cuando apuntas el teléfono de alguien en una nota. Ejercicio (papel y lápiz): escribe 5 "variables" para guardar datos sobre ti mismo. Módulo 2 - Condicionales: son decisiones del programa. Como "si llueve, coge el paraguas; si no, no". Ejercicio: escribe 3 decisiones cotidianas en formato si/entonces/si-no. [Filtrado: no se mencionan comandos de terminal, no se pide instalar nada, no se usa notación matemática formal.]'
ws2['L27'] = 'Material filtrado (sin instalaciones, sin jerga, sin matemáticas avanzadas): Módulo 1 - Variables: "Una variable es como una nota adhesiva digital: le pones un nombre y guardas ahí un dato." Ejercicio con papel: dibuja 3 notas adhesivas y escribe en cada una un nombre de variable y su valor. Módulo 2 - Condicionales: "El programa toma decisiones como tú. Si la nota es mayor que 10, pasaste; si no, repites." Ejercicio con papel: escribe 3 decisiones cotidianas en formato si/entonces/si-no. Módulo 3 - Bucles: "Un bucle repite una acción. Como cuando tu alarma suena cada día a las 7am." Ejercicio: escribe en pseudocódigo cuántas veces suena tu alarma en una semana. [Todos los ejercicios son de lápiz y papel o pseudocódigo sin ejecutar.]'
ws2['M27'] = 'Verificación de supuestos: El estudiante no sabe qué es una variable en matemáticas → las analogías evitarán esa referencia. No tiene editor instalado → usaremos solo pseudocódigo o Python en Colab (sin instalación). No ha visto un error de compilación → los errores comunes se presentarán como "mensajes de aviso del programa", no como errores técnicos. Material (filtrado): Módulo 1 - Variables: "Imagina que eres un chef y tienes frascos etiquetados. nombre_del_chef = "Ana". Eso es una variable." Ejercicio en Google Colab (sin instalación): nombre = input("¿Cómo te llamas?"), print("Hola", nombre). Módulo 2 - Condicionales: "El programa decide como tú en el supermercado: si hay leche, coge 1; si no, coge 2." [Continúa sin jerga técnica ni instalaciones.]'

ws2['K33'] = 'Sí. La V0 mezclaba conceptos de diferentes niveles sin filtro. La VP aplicó tres criterios de filtro claros (sin matemáticas avanzadas, sin instalación, con papel y lápiz), lo que eliminó contenido inapropiado para principiantes y concentró el material en lo esencial.'
ws2['K34'] = 'La VP filtraba el contenido pero no verificaba los supuestos de partida. La VR comenzó declarando explícitamente lo que el modelo asumía sobre el estudiante y luego aplicó el filtro, lo que produjo materiales más granulares en el nivel de personalización: por ejemplo, ofrecer Colab en lugar de un IDE local.'
ws2['K35'] = 'Diferencia según la UI programada'
ws2['K36'] = 'Claude, a diferencia de algunos otros modelos, interpreta el filtro semántico como una restricción de post-procesamiento: genera el contenido y luego verifica si cada elemento cumple los criterios antes de incluirlo. Esto se debe al entrenamiento con RLHF que optimiza la precisión en seguir instrucciones de restricción. Modelos con menos ajuste fino de instrucción podrían ignorar el filtro tras la mitad de la respuesta, especialmente en respuestas largas.'

# ---- PE11 - TEMPLATE ----
ws2['O23'] = '[--]'
ws2['P23'] = 'Usaremos PE11 para proporcionarle al modelo una plantilla fija de ficha didáctica que debe rellenar para cada concepto: nombre, analogía, explicación técnica, ejercicio, error común y criterio de logro.'
ws2['Q23'] = 'Usaremos PE11 + PE15 (Receta) porque la plantilla define la estructura de cada ficha Y la receta define el orden de pasos para que el docente los use en clase, haciendo el material tanto bien estructurado como operativamente claro.'

ws2['O25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['P25'] = 'Para cada concepto de programación básica (variables, condicionales, bucles, funciones), completa la siguiente plantilla: FICHA DIDÁCTICA — Concepto: [nombre] | Analogía cotidiana: [descripción] | Explicación técnica simple: [en máx. 2 oraciones] | Ejercicio práctico: [descripción del ejercicio] | Error más común: [descripción] | Criterio de logro: [cómo sabe el docente que el estudiante lo entendió].'
ws2['Q25'] = 'Para cada concepto de programación básica (variables, condicionales, bucles, funciones), completa esta plantilla: FICHA DIDÁCTICA — Concepto | Analogía | Explicación | Ejercicio | Error común | Criterio de logro. Además, al final de las 4 fichas, agrega una RECETA DE USO EN CLASE: los pasos exactos que debe seguir el docente para presentar cada ficha, en el orden óptimo.'

ws2['O27'] = 'Variables: son nombres que guardan datos. Ejercicio: crea 5 variables. Condicionales: son decisiones. Ejercicio: escribe un if/else. Bucles: repiten acciones. Ejercicio: contador del 1 al 10. Funciones: agrupan instrucciones. Ejercicio: crea una función saludo.'
ws2['P27'] = 'FICHA 1 — Variables | Analogía: etiqueta en un frasco | Explicación: una variable es un nombre que el programa usa para recordar un dato. Cuando escribes edad = 20, el programa recuerda que "edad" vale 20. | Ejercicio: crea 5 variables para guardar tu nombre, edad, ciudad, nota favorita y color favorito. | Error común: usar espacios en el nombre (mi variable = 5 → incorrecto; mi_variable = 5 → correcto). | Criterio de logro: el estudiante puede crear y modificar una variable sin ayuda. — FICHA 2 — Condicionales | Analogía: semáforo | Explicación: el programa decide qué hacer según una condición. Si la condición es verdadera, hace A; si no, hace B. | Ejercicio: escribe un if/else que evalúe si una nota es aprobatoria. | Error común: usar = en vez de == para comparar. | Criterio: el estudiante escribe un if/else correcto con al menos dos ramas. — FICHA 3 — Bucles | Analogía: playlist en repeat | Explicación: el bucle repite un bloque de código mientras la condición sea verdadera. | Ejercicio: imprime los números del 1 al 10. | Error común: olvidar actualizar el contador (bucle infinito). | Criterio: el estudiante produce un bucle que termina. — FICHA 4 — Funciones | Analogía: botón de microondas preprogramado | Explicación: una función agrupa instrucciones bajo un nombre para reutilizarlas. | Ejercicio: crea una función que salude a cualquier persona dado su nombre. | Error común: definir la función pero no llamarla. | Criterio: el estudiante llama a su función con diferentes argumentos.'
ws2['Q27'] = '[Mismas 4 fichas que VP] RECETA DE USO EN CLASE: Paso 1 — Presenta la analogía (2 min): muestra el objeto cotidiano (frasco, semáforo, playlist, microondas) físicamente o en imagen. Paso 2 — Explica el concepto técnico (3 min): una sola oración, sin tecnicismos adicionales. Paso 3 — Muestra el código en pantalla (2 min): escríbelo tú primero, en silencio, mientras los estudiantes observan. Paso 4 — Haz el ejercicio en vivo (5 min): resuelve el ejercicio junto con los estudiantes pidiendo que dicten el código. Paso 5 — Señala el error común (1 min): comete el error intencionalmente y muestra el mensaje de aviso. Paso 6 — Evalúa el criterio de logro (3 min): pide a un estudiante que lo haga solo desde cero.'

ws2['O33'] = 'Sí. La V0 generaba listas sin estructura consistente entre conceptos. La VP impuso una plantilla de 6 campos por ficha, lo que hace el material directamente usable en clase sin reelaboración.'
ws2['O34'] = 'La VP producía fichas completas pero sin instrucciones de uso. La VR añadió la Receta de uso en clase, que convierte el material de "referencia" a "guion operativo": el docente sabe exactamente qué hacer en cada minuto de la presentación.'
ws2['O35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws2['O36'] = 'La plantilla (PE11) restringe la forma de cada ficha; la receta (PE15) restringe el orden de uso. Combinados, el modelo opera en un espacio generativo de "relleno de formulario + secuencia de pasos", que tiene mucha menos varianza que la generación libre. El resultado es un material de alta consistencia interna, coherente con la teoría de que las restricciones de forma y secuencia se amplifican mutuamente.'

# ---- PE12 - EXPANSIÓN DE ESQUEMA ----
ws2['S23'] = '[--]'
ws2['T23'] = 'Usaremos PE12 para darle al modelo un esquema mínimo (solo los nombres de los conceptos y sus relaciones) y pedirle que lo expanda en material didáctico completo, manteniendo la jerarquía del esquema original.'
ws2['U23'] = 'Usaremos PE12 + PE14 (Juego) porque al expandir el esquema en formato de juego didáctico, el material gana una capa de motivación extrínseca que facilita la retención en estudiantes jóvenes.'

ws2['S25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['T25'] = 'Tengo este esquema básico de los conceptos de programación para principiantes: Programación básica → 1. Variables (almacenar datos) → 2. Condicionales (tomar decisiones) → 3. Bucles (repetir acciones) → 4. Funciones (reutilizar código). Expande este esquema en materiales didácticos completos, respetando la jerarquía y el orden indicados. Para cada nodo, incluye explicación, analogía, ejercicio y error común.'
ws2['U25'] = 'Tengo este esquema: Programación básica → Variables → Condicionales → Bucles → Funciones. Expande este esquema en un juego didáctico (tipo misiones o niveles) donde cada concepto sea un nivel que el estudiante debe superar. Cada nivel debe tener: misión (qué debe lograr), explicación del concepto, analogía, ejercicio-reto y condición de avance al siguiente nivel.'

ws2['S27'] = '1. Variables: guardan datos. 2. Condicionales: toman decisiones. 3. Bucles: repiten acciones. 4. Funciones: reutilizan código. Cada uno con ejercicio básico.'
ws2['T27'] = 'Esquema expandido: NIVEL 1 — Variables. Explicación: son contenedores con nombre para guardar datos. Analogía: etiquetas en cajas de mudanza. Ejercicio: crea 5 variables para describir a tu personaje favorito. Error común: usar espacios en el nombre. — NIVEL 2 — Condicionales. Explicación: permiten al programa tomar decisiones. Analogía: el árbitro del partido (si la pelota sale, es falta). Ejercicio: escribe un condicional que evalúe si una temperatura es fría, tibia o caliente. Error común: = vs ==. — NIVEL 3 — Bucles. Explicación: repiten instrucciones automáticamente. Analogía: la función repeat de una canción. Ejercicio: imprime los números del 1 al 20. Error común: bucle infinito. — NIVEL 4 — Funciones. Explicación: bloques de código reutilizables con nombre. Analogía: receta de cocina guardada. Ejercicio: crea una función que calcule el área de un rectángulo. Error común: definir sin llamar.'
ws2['U27'] = 'JUEGO: "CÓDIGO QUEST" — 4 misiones para convertirte en programador. MISIÓN 1 — EL ALMACÉN (Variables): Tu misión es crear un inventario digital. Concepto: una variable es un espacio con nombre donde guardas un dato. Analogía: los cajones de tu cuarto con etiqueta. Reto: crea 5 variables para tu personaje (nombre, nivel, puntos, arma, ciudad). Condición de avance: el estudiante puede crear y modificar variables sin ayuda. MISIÓN 2 — LA ENCRUCIJADA (Condicionales): El camino se divide. El programa debe decidir qué ruta tomar. Concepto: if/else evalúa una condición y elige un camino. Analogía: la bifurcación de un videojuego (¿atacas o huyes?). Reto: escribe el código de decisión para una batalla (si puntos > 50, ataca; si no, corre). Condición de avance: escribe un if/else correcto con dos ramas. MISIÓN 3 — EL EJERCITO (Bucles): Necesitas entrenar 10 soldados. Hacerlo uno a uno es lento. Concepto: el bucle repite la misma instrucción N veces. Analogía: el botón de "entrenar unidad ×10" de un juego de estrategia. Reto: usa un bucle para entrenar a los 10 soldados con una sola instrucción. Condición de avance: el estudiante produce un bucle que termina y no genera error. MISIÓN 4 — EL HÉROE (Funciones): Tienes un hechizo poderoso que quieres usar en cualquier batalla. Concepto: las funciones son hechizos guardados que puedes lanzar cuando quieras. Analogía: los ataques especiales de los videojuegos (botón Y = habilidad especial). Reto: crea la función ataque_especial(enemigo) y úsala 3 veces en diferentes batallas. Condición de avance: el estudiante define y llama a su función con diferentes argumentos.'

ws2['S33'] = 'Sí. La V0 generaba material sin jerarquía explícita. La VP partió del esquema del docente y lo respetó fielmente, asegurando que el material siga exactamente la progresión conceptual planificada, no la que el modelo elegiría por defecto.'
ws2['S34'] = 'La VP expandía el esquema en fichas didácticas estándar. La VR lo convirtió en un juego por niveles (Código Quest), lo que añade narrativa, progresión de dificultad explícita y condiciones de avance claras, transformando el material de "explicaciones para leer" a "retos para completar".'
ws2['S35'] = 'Diferencia según la UI programada'
ws2['S36'] = 'La expansión de esquema con formato de juego activa en Claude un modo de generación narrativa-estructurada diferente al modo expositivo estándar. Claude, al haber sido entrenado con gran cantidad de contenido de gamificación educativa, reconoce el patrón "misión + concepto + reto + condición de avance" y lo ejecuta con alta fidelidad. Otros modelos con menos datos de gamificación educativa en su entrenamiento producirían versiones menos coherentes del juego o colapsarían el formato a una lista numerada estándar.'

# ---- PE13 - CHECKLIST ----
ws2['W23'] = '[--]'
ws2['X23'] = 'Usaremos PE13 para pedirle al modelo que genere una lista de verificación que el docente pueda usar antes, durante y después de cada sesión para asegurarse de que los estudiantes comprenden cada concepto.'
ws2['Y23'] = 'Usaremos PE13 + PE09 (Cadena de Pensamiento) porque al combinar la checklist con el razonamiento explícito, el modelo puede justificar por qué cada ítem de la lista es necesario, haciendo la checklist más comprensible y adaptable para el docente.'

ws2['W25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['X25'] = 'Crea una checklist de verificación para docentes que enseñan programación básica a principiantes. La checklist debe tener tres secciones: (1) Antes de la clase: qué debe preparar el docente, (2) Durante la clase: qué señales indican que los estudiantes comprenden o no, (3) Después de la clase: cómo evaluar si el objetivo se logró. Una checklist por concepto (variables, condicionales, bucles, funciones).'
ws2['Y25'] = 'Razona paso a paso qué necesita verificar un docente en cada fase (antes, durante, después) para asegurar que los estudiantes de programación básica comprenden cada concepto. Muestra ese razonamiento y luego genera una checklist justificada para cada concepto (variables, condicionales, bucles, funciones).'

ws2['W27'] = 'Checklist general: ¿Expliqué el concepto? ¿Puse un ejemplo? ¿Los estudiantes hicieron un ejercicio? ¿Evaluaste si lo entendieron? Para variables, condicionales, bucles y funciones, repite el mismo proceso.'
ws2['X27'] = 'CHECKLIST — VARIABLES. ANTES: ☐ Preparé al menos una analogía visual (imagen de caja/etiqueta). ☐ Tengo 2 ejemplos de código mínimos. ☐ Anticipé los errores de nombres con espacios. DURANTE: ☐ Los estudiantes pueden decir en voz alta qué guarda cada variable. ☐ Detecté si alguien confunde = con == (señal: errores en ejercicios de comparación). ☐ Todos completaron el ejercicio de 5 variables. DESPUÉS: ☐ El estudiante puede crear una variable sin ver el ejemplo. ☐ Puede modificar el valor de una variable existente. — CHECKLIST — CONDICIONALES. ANTES: ☐ Preparé el ejemplo del semáforo o decisión cotidiana. ☐ Tengo un ejercicio con dos casos (verdadero y falso). DURANTE: ☐ Los estudiantes distinguen cuándo se ejecuta el bloque if y cuándo el else. ☐ Nadie usó = en lugar de ==. DESPUÉS: ☐ El estudiante escribe un if/else correcto desde cero. — [Igual para Bucles y Funciones]'
ws2['Y27'] = 'Razonamiento: Antes de la clase, el docente necesita verificar que tiene los recursos mínimos (analogía + código + ejercicio). Durante la clase, necesita señales observables de comprensión o confusión. Después, necesita criterios de éxito medibles. Justificación de cada ítem: la analogía visual es crítica porque los principiantes aprenden por anclajes concretos antes que abstractos; los errores típicos deben anticiparse porque si el docente los desconoce no sabrá diagnosticarlos; los criterios post-clase deben ser conductuales ("puede hacer X sin ayuda") y no declarativos ("dice que entendió"). CHECKLIST JUSTIFICADA — VARIABLES [mismos ítems que VP + columna de justificación]. — [Continúa para los 4 conceptos]'

ws2['W33'] = 'Sí. La V0 no incluía ningún instrumento de verificación para el docente. La VP proporcionó una checklist estructurada en tres fases (antes/durante/después) por concepto, lo que convierte el material de "contenido pasivo" a "guía activa de gestión del aula".'
ws2['W34'] = 'La VP producía checklists funcionales pero sin explicar por qué cada ítem era importante. La VR justificó cada ítem con razonamiento pedagógico, lo que permite al docente priorizar ítems críticos y adaptar la lista a su contexto sin perder la lógica original.'
ws2['W35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws2['W36'] = 'La checklist (PE13) restringe el formato a ítems binarios verificables (☐). La cadena de pensamiento (PE09) añade una columna de justificación. Combinados, el modelo opera en el modo "tabla de ítems + columna de razonamiento", que tiene muy poca varianza generativa porque cada celda cumple una función fija. Esto es coherente con la teoría de que los formatos tabulares + razonamiento explícito son los más eficientes para activar la capacidad analítica del modelo.'

# ---- PE14 - JUEGO ----
ws2['AA23'] = '[--]'
ws2['AB23'] = 'Usaremos PE14 para diseñar un juego didáctico de preguntas y retos que el docente pueda usar al final de cada módulo para evaluar si los estudiantes comprendieron el concepto, de forma lúdica y sin la presión de un examen formal.'
ws2['AC23'] = 'Usaremos PE14 + PE12 (Expansión de Esquema) porque al combinar el juego con un esquema de progresión de dificultad, el docente tiene tanto el formato lúdico como la garantía de que los retos escalan adecuadamente de nivel en nivel.'

ws2['AA25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['AB25'] = 'Diseña un juego didáctico de trivia y retos para evaluar la comprensión de programación básica en principiantes. El juego debe tener 4 rondas (una por concepto: variables, condicionales, bucles, funciones). Cada ronda: 3 preguntas de opción múltiple + 1 reto práctico. Incluye respuestas correctas y retroalimentación para cada opción incorrecta.'
ws2['AC25'] = 'Tengo este esquema de dificultad para el juego: Nivel 1 (Reconocimiento) → Nivel 2 (Comprensión) → Nivel 3 (Aplicación). Expande este esquema en un juego de evaluación por niveles para cada concepto de programación básica. Cada nivel del juego debe tener preguntas del tipo correspondiente (reconocer definición → explicar con analogía → resolver un reto práctico).'

ws2['AA27'] = '1. ¿Qué es una variable? a) Una instrucción que se repite b) Un nombre que guarda un dato c) Una decisión del programa. Respuesta: b. 2. ¿Cuándo se usa un bucle? a) Para guardar datos b) Para repetir acciones c) Para definir nombres. Respuesta: b. [Y así para los 4 conceptos]'
ws2['AB27'] = 'JUEGO DE TRIVIA — PROGRAMACIÓN BÁSICA. RONDA 1 — VARIABLES. Pregunta 1: ¿Cuál de estas es una variable válida en Python? a) mi variable = 5 b) mi_variable = 5 c) 1variable = 5. Respuesta: b. Retroalimentación a: los nombres de variables no pueden tener espacios. Retroalimentación c: los nombres no pueden empezar con un número. Pregunta 2: Si escribes edad = 25 y luego edad = 30, ¿cuánto vale edad? a) 25 b) 30 c) 25 y 30 a la vez. Respuesta: b. El nuevo valor reemplaza al anterior. Pregunta 3: ¿Para qué sirve una variable? a) Para repetir una instrucción b) Para guardar un dato con un nombre c) Para tomar una decisión. Respuesta: b. RETO PRÁCTICO: crea 5 variables que describan a tu superhéroe favorito (nombre, poder, ciudad, puntos de vida, arma). — [RONDA 2, 3 y 4 con la misma estructura para condicionales, bucles y funciones]'
ws2['AC27'] = 'JUEGO POR NIVELES — VARIABLES. NIVEL 1 (Reconocimiento): ¿Cuál de estas es una variable? a) if edad > 18 b) nombre = "Ana" c) for i in range(10). Respuesta: b. NIVEL 2 (Comprensión): Explica con tus palabras (o con la analogía de la caja) por qué nombre = "Ana" es una variable y for i in range(10) no lo es. NIVEL 3 (Aplicación): Escribe el código para guardar tu nombre, tu edad y tu ciudad en tres variables, luego cambia el valor de la edad por el doble. — [Misma estructura de 3 niveles para condicionales, bucles y funciones]'

ws2['AA33'] = 'Sí. La V0 no incluía ningún mecanismo de evaluación. La VP añadió un juego de trivia con preguntas, respuestas y retroalimentación diferenciada por opción incorrecta, lo que convierte la evaluación en un momento de aprendizaje adicional (feedback inmediato).'
ws2['AA34'] = 'La VP tenía el formato de trivia pero sin distinción de niveles cognitivos. La VR (con PE12) organizó las preguntas en tres niveles (reconocimiento → comprensión → aplicación), siguiendo la taxonomía de Bloom, lo que permite al docente diagnosticar en qué nivel cognitivo se quedó cada estudiante.'
ws2['AA35'] = 'Diferencia en los datos de entrenamiento'
ws2['AA36'] = 'La taxonomía de Bloom (recordar → comprender → aplicar → analizar → evaluar → crear) es un marco pedagógico ampliamente representado en los datos de entrenamiento de Claude a través de libros de didáctica, papers de educación y materiales curriculares. Al pedir al modelo que expanda el esquema de tres niveles (reconocimiento → comprensión → aplicación), activó ese marco implícitamente y generó preguntas coherentes con cada nivel cognitivo sin necesidad de que el usuario lo nombrara explícitamente.'

# ---- PE15 - RECETA ----
# Estructura sheet: AE17 is PE15, AE18/AF18/AG18 are V0/VP/VR
ws2['AE23'] = '[--]'
ws2['AF23'] = 'Usaremos PE15 para pedirle al modelo que genere una receta didáctica paso a paso: los ingredientes (materiales necesarios), la preparación (secuencia de actividades) y el resultado esperado (indicadores de logro).'
ws2['AG23'] = 'Usaremos PE15 + PE11 (Template) porque la receta define el proceso y la plantilla define la estructura de cada paso, asegurando que cada actividad de la receta sea presentada de forma consistente y usable.'

ws2['AE25'] = 'Crea materiales didácticos para enseñar programación básica a principiantes.'
ws2['AF25'] = 'Crea una receta didáctica para enseñar programación básica a principiantes. La receta debe incluir: INGREDIENTES (materiales, herramientas y conocimientos previos necesarios), PREPARACIÓN (secuencia paso a paso de actividades para la sesión de clase, con tiempo estimado para cada paso) y RESULTADO ESPERADO (qué debe saber hacer el estudiante al final y cómo verificarlo).'
ws2['AG25'] = 'Crea una receta didáctica para enseñar programación básica a principiantes. La receta debe seguir esta plantilla para cada paso de la preparación: Paso N | Actividad | Duración | Materiales necesarios | Indicador de éxito. Además incluye secciones de Ingredientes y Resultado esperado.'

ws2['AE27'] = 'Para enseñar programación básica: necesitas una computadora y proyector. Empieza explicando qué es programar, luego muestra ejemplos, haz ejercicios y evalúa al final.'
ws2['AF27'] = 'RECETA DIDÁCTICA — PROGRAMACIÓN BÁSICA. INGREDIENTES: Materiales: proyector o pizarra, computadoras o tablets (1 por cada 2 estudiantes), acceso a Python online (Google Colab, sin instalación), fichas impresas con los conceptos. Herramientas: editor de código online, temporizador visible para los estudiantes. Conocimientos previos necesarios: ninguno técnico; saber usar un navegador web. PREPARACIÓN (90 min de sesión): Paso 1 — Activación (10 min): pregunta "¿qué crees que hace una computadora cuando le das una instrucción?". Paso 2 — Analogía de la receta de cocina (5 min): el código es una receta; el programador es el chef; la computadora es quien cocina. Paso 3 — Variables (15 min): explicación + analogía + ejercicio individual. Paso 4 — Condicionales (15 min): idem. Paso 5 — Bucles (15 min): idem. Paso 6 — Funciones (15 min): idem. Paso 7 — Integración (10 min): ejercicio que combine los 4 conceptos. Paso 8 — Cierre (5 min): cada estudiante dice una cosa que aprendió y una duda. RESULTADO ESPERADO: el estudiante puede escribir un programa de 10-15 líneas que use los 4 conceptos sin copiar de un ejemplo.'
ws2['AG27'] = 'RECETA DIDÁCTICA — PROGRAMACIÓN BÁSICA. INGREDIENTES: [igual que VP] PREPARACIÓN: Paso 1 | Activación | 10 min | Pizarra o proyector | El estudiante puede mencionar al menos una instrucción que le daría a una computadora. Paso 2 | Analogía de la receta | 5 min | Imagen de receta de cocina | El estudiante dice con sus palabras qué es el código. Paso 3 | Variables | 15 min | Google Colab + ficha PE11 de variables | El estudiante crea 5 variables correctas sin error de nombre. Paso 4 | Condicionales | 15 min | Ficha PE11 de condicionales | El estudiante escribe un if/else que cubre dos casos. Paso 5 | Bucles | 15 min | Ficha PE11 de bucles | El estudiante produce un bucle que termina. Paso 6 | Funciones | 15 min | Ficha PE11 de funciones | El estudiante define y llama a su función. Paso 7 | Integración | 10 min | Enunciado integrador | El estudiante combina los 4 conceptos en un programa de 15 líneas. Paso 8 | Cierre | 5 min | Post-it o formulario digital | El estudiante identifica una cosa aprendida y una duda. RESULTADO ESPERADO: [igual que VP]'

ws2['AE33'] = 'Sí. La V0 daba una secuencia vaga sin tiempos ni materiales específicos. La VP proporcionó una receta completa con tres secciones (ingredientes, preparación, resultado), tiempos estimados por paso y criterios de logro, lo que hace el material directamente ejecutable por cualquier docente.'
ws2['AE34'] = 'La VP tenía la receta pero los pasos eran descripciones en prosa. La VR (con PE11) estructuró cada paso en 5 campos fijos (paso, actividad, duración, materiales, indicador), lo que permite al docente escanear rápidamente cualquier paso sin leer el párrafo completo.'
ws2['AE35'] = 'Diferencia porque se pudo acotar más el espacio de búsqueda'
ws2['AE36'] = 'La receta (PE15) ya es un patrón de secuencia estructurada. Al añadir la plantilla (PE11) con campos fijos por paso, el modelo opera en el modo más restringido posible: cada celda de la tabla tiene una función semántica predefinida. Esto produce la respuesta con menor entropía de todas las combinaciones posibles, y la más directamente usable operativamente, porque elimina toda ambigüedad sobre qué información corresponde a cada campo.'

wb.save('/home/claude/Plantilla_prompts_completa.xlsx')
print("Guardado OK")
PYEOF
python3 /home/claude/fill_plantilla.py
Salida

Guardado OK
Listo
